### PR TITLE
Version bump.

### PR DESCRIPTION
**Pull request by mozbhearsum**

### CODE REVIEW

**Comment by rail** [comment]
> It's weird that there is no TC report, but...

I think this is because TC is not enabled in your repo. IIRC TC tries to use it for PR tasks.

**Comment by mozbhearsum** [comment]
It worked fine for #974...

**Comment by rail** [comment]
> It worked fine for #974...

I think because it was not a fork, but a branch in this repo

**Comment by rail** [comment]
huh, now it's green

**Comment by mozbhearsum** [comment]
I think Taskcluster just missed the PR or something. It triggered after a close/reopen of the PR.

**Pull request merged**
