### PR TITLE
Get rid of workaround for mysql permission issue.

### PR DESCRIPTION
**Pull request by bhearsum**
My image stopped working after I rebuilt with https://github.com/docker-library/mysql/commit/a6f4c23621421bb708ad44616532d3d1cf44f6bf#diff-17ed820d5141a5e8565a0431e5385daeR24. Looks like mysql fixed this issue upstream.

@rail - what do you think?

### CODE REVIEW

**Comment by rail** [comment]
If it works, I'm all in for less work arounds!

**Comment by nthomas-mozilla** [comment]
Unfortunately it's not working for me:
```
$ docker-compose up balrogdb
Creating balrog_balrogdb_1
Attaching to balrog_balrogdb_1
balrogdb_1 | 2016-05-31T05:04:39.488448Z 0 [Warning] Can't create test file /var/lib/mysql/26a51217dc47.lower-test
balrogdb_1 | 2016-05-31T05:04:39.488530Z 0 [Note] mysqld (mysqld 5.7.12) starting as process 1 ...
balrogdb_1 | 2016-05-31T05:04:39.490774Z 0 [Warning] Can't create test file /var/lib/mysql/26a51217dc47.lower-test
balrogdb_1 | 2016-05-31T05:04:39.491103Z 0 [Warning] Can't create test file /var/lib/mysql/26a51217dc47.lower-test
balrogdb_1 | 2016-05-31T05:04:39.494881Z 0 [Note] InnoDB: PUNCH HOLE support available
balrogdb_1 | 2016-05-31T05:04:39.495053Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
balrogdb_1 | 2016-05-31T05:04:39.495252Z 0 [Note] InnoDB: Uses event mutexes
balrogdb_1 | 2016-05-31T05:04:39.495290Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
balrogdb_1 | 2016-05-31T05:04:39.495502Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
balrogdb_1 | 2016-05-31T05:04:39.495677Z 0 [Note] InnoDB: Using Linux native AIO
balrogdb_1 | 2016-05-31T05:04:39.498019Z 0 [Note] InnoDB: Number of pools: 1
balrogdb_1 | 2016-05-31T05:04:39.502094Z 0 [Note] InnoDB: Using CPU crc32 instructions
balrogdb_1 | 2016-05-31T05:04:39.508285Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
balrogdb_1 | 2016-05-31T05:04:39.517254Z 0 [Note] InnoDB: Completed initialization of buffer pool
balrogdb_1 | 2016-05-31T05:04:39.519235Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
balrogdb_1 | 2016-05-31T05:04:39.529731Z 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must be writable
balrogdb_1 | 2016-05-31T05:04:39.529879Z 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must be writable
balrogdb_1 | 2016-05-31T05:04:39.530055Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
balrogdb_1 | 2016-05-31T05:04:40.131825Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
balrogdb_1 | 2016-05-31T05:04:40.131977Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
balrogdb_1 | 2016-05-31T05:04:40.132172Z 0 [ERROR] Failed to initialize plugins.
balrogdb_1 | 2016-05-31T05:04:40.132351Z 0 [ERROR] Aborting
balrogdb_1 |
balrogdb_1 | 2016-05-31T05:04:40.132573Z 0 [Note] Binlog end
balrogdb_1 | 2016-05-31T05:04:40.132661Z 0 [Note] Shutting down plugin 'MyISAM'
balrogdb_1 | 2016-05-31T05:04:40.132865Z 0 [Note] Shutting down plugin 'CSV'
balrogdb_1 | 2016-05-31T05:04:40.133752Z 0 [Note] mysqld: Shutdown complete
balrogdb_1 |
balrog_balrogdb_1 exited with code 1
```
I have docker 1.10.0 on OS X, with mysql image 5.7, id e583afc2f0e4, from 13 days ago. Going back to the rev prior to this landing works.

**Comment by nthomas-mozilla** [comment]
Updating to docker 1.11.1 doesn't help, so the only thing I don't have up to date is Virtualbox (5.0.14 instead of 5.0.20).

**Comment by bhearsum** [comment]
Reverting this for now - I'll find a new workaround, or case this one on Mac.

**Comment by bhearsum** [comment]
Over in https://github.com/docker-library/mysql/issues/175 someone noted that removing the script + using the Docker beta worked for them. I got access to the Docker beta and tried it for myself - it worked. Seems that the new Docker may be native, because it doesn't appear to use Virtualbox either.

Once it's released, maybe we can try this again.

**Pull request merged**
