### PR TITLE
bug 1304561- Move the 'View Data' button to be next to the other buttons

### PR DESCRIPTION
**Pull request by Shruti9520**

### CODE REVIEW

**Comment by tpingili** [comment]
Hi Shruti9520, 

Are you still working on it? I would like to pick it up otherwise.

**Comment by Shruti9520** [comment]
@tpingili  Yes, I am working on this.:)

**Comment by Shruti9520** [comment]
@mozbhearsum Will you please re-send me, the collaboration invite? I am really sorry for the inconvenience.

**Comment by mozbhearsum** [comment]
@Shruti9520 - done!

**Comment by mozbhearsum** [comment]
Sorry @Shruti9520, this ended up getting fixed in #262. Please let me know if you want to work on something else instead.

**Pull request closed without merging**
