### PR TITLE
Bug 1113111 - tracebacks when a platform exists in a blob but has no …

### PR DESCRIPTION
**Pull request by nurav**
Changed `dict[key]` access to `dict.get(key, default)`.

### CODE REVIEW

**Comment by bhearsum** [comment]
This seems okay, can you add a test to ensure we don't regress it again? You'll need something similar to https://github.com/mozilla/balrog/blob/master/auslib/test/blobs/test_apprelease.py#L72

**Comment by nurav** [comment]
Sure! On it.

**Comment by bhearsum** [comment]
I was doing some final testing of this and I realized that there's still a case that's not handled here, specifically if a KeyError is hit on line 67. Can you fix that as well and add a test?

There's a few pep8 issues to deal with:
auslib/blobs/apprelease.py:61:1: E101 indentation contains mixed spaces and tabs
	if locale not in self['platforms'].get(platform, {}) \
^
auslib/blobs/apprelease.py:61:1: W191 indentation contains tabs
	if locale not in self['platforms'].get(platform, {}) \
^
auslib/blobs/apprelease.py:62:1: E101 indentation contains mixed spaces and tabs
                                          .get('locales', {}):
^
auslib/blobs/apprelease.py:62:43: E127 continuation line over-indented for visual indent
                                          .get('locales', {}):
                                          ^

**Comment by bhearsum** [comment]
I triggered tests on this in https://tools.taskcluster.net/task-inspector/#et5cZZCIRPyWrMz1c9DyBQ/0, which passed. The code looks good to me as well. Thank you very much!

**Pull request merged**
