### PR TITLE
Bug 1333875 - don't update "scheduled_by" field when merging in updat…

### PR DESCRIPTION
**Pull request by galbie**
Fixed the bug by using `scheduled_by` of `sc_table` instead of `changed_by`.

I was playing around after the fix and when I found out that even if I `update` in [http://localhost:8080/rules/scheduled_changes](http://localhost:8080/rules/scheduled_changes), it still didn't update `scheduled_by`. 
Is this what is expected of the fix?

### CODE REVIEW

**Comment by aksareen** [comment]
Nit: Fix PEP8 warning : 
auslib/test/test_db.py:1337:18: E225 missing whitespace around operator
        new_row =self.sc_table.select(where=[self.sc_table.sc_id == 4])[0]

**Comment by galbie** [comment]
Hello, I fixed the PEP 8 warning

**Comment by mozbhearsum** [comment]
Thank you for this, @galbie! Let us know if want help finding another bug to work on.

**Comment by galbie** [comment]
@mozbhearsum Hi, I don't know if this is a good place, but I would love to work on another bug.
It was hard, but it was so much fun for me.

**Comment by NinadBhat** [comment]
@galbie have a look at [bugs](https://bugzilla.mozilla.org/buglist.cgi?list_id=13406850&emailtype1=exact&status_whiteboard_type=allwordssubstr&emailassigned_to1=1&status_whiteboard=%5Bgood%20first%20bug%5D&email1=nobody%40mozilla.org&resolution=---&query_format=advanced&component=Balrog%3A%20Backend&component=Balrog%3A%20Frontend). If you like anything please comment on the bug.

**Comment by aksareen** [comment]
@galbie . If you need help , feel free to ping any of us on IRC. We're usually available from  1400 UTC to 2100 UTC

**Pull request merged**
