### PR TITLE
Bug 1333571 - Implemented dynamic titles by adding a new service to set the page title

### PR DESCRIPTION
**Pull request by arn197**

### CODE REVIEW

**Comment by arn197** [comment]
I have made the required changes, and also shortened the titles to mostly fit within the tab width. Please have a look :)

**Comment by NinadBhat** [comment]
Looks good to me. Suggesting two changes below(please wait for confirmation from @mozbhearsum on this)
1. I think "Permissions - Balrog Admin" would be better as on using "Balrog Admin Permissions" I can only see "Balrog Admin - Per..." rest gets hidden.
2. To maintain consistency, it would also be better tho have "Balrog Admin - Scheduled Release Changes" or "Scheduled Release Changes - Balrog Admin" depending upon the resolution of point 1.

Great work with the changes. Thanks a lot for your contribution.

**Comment by arn197** [comment]
I have made the changes.
P.S - sorry for the delay, I had exams until yesterday.

**Comment by NinadBhat** [comment]
Looks good now. Thanks a lot for your work. 
If you are looking for more bugs to solve you can have a look at [ Good First Bug](https://bugzilla.mozilla.org/buglist.cgi?list_id=13406850&emailtype1=exact&status_whiteboard_type=allwordssubstr&emailassigned_to1=1&status_whiteboard=%5Bgood%20first%20bug%5D&email1=nobody%40mozilla.org&resolution=---&query_format=advanced&component=Balrog%3A%20Backend&component=Balrog%3A%20Frontend) or [here](https://bugzilla.mozilla.org/buglist.cgi?list_id=13406852&emailtype1=exact&status_whiteboard_type=allwordssubstr&emailassigned_to1=1&status_whiteboard=%5Bready%5D&email1=nobody%40mozilla.org&resolution=---&query_format=advanced&component=Balrog%3A%20Backend&component=Balrog%3A%20Frontend).

**Pull request merged**
