### PR TITLE
Install pcre packages to fix uwsgi routing.

### PR DESCRIPTION
**Pull request by mozbhearsum**

### CODE REVIEW

**Comment by mozbhearsum** [comment]
Details about this in https://github.com/docker-library/python/issues/132

**Comment by rail** [comment]
:ship: it

**Comment by mozbhearsum** [comment]
Turns out an upstream fix is coming...

**Comment by mozbhearsum** [comment]
@njirap - you can merge this to fix yourself up until the upstream fix arrives.

**Pull request closed without merging**
