### PR TITLE
[rule-delete-modal] Added comment and other Rule information

### PR DESCRIPTION
**Pull request by njirap**
Closes-bug: #1150538

### CODE REVIEW

**Comment by bhearsum** [comment]
You'll need to send a PR for the balrog-ui repo for this. Unfortunately, submodule changes don't make good PRs :(

**Comment by njirap** [comment]
Hi bhearsum.. i think the balrog-ui pull request is already accepted..
https://github.com/mozilla/balrog-ui/commit/a9943dc63d8bd308ee38d03db4e2225dd268c95e#commitcomment-16715503

**Comment by njirap** [comment]
On second look it doesnt look accepted..

https://github.com/mozilla/balrog-ui/pull/18

**Comment by bhearsum** [comment]
Can you update this to use the merge commit revision (47fcfe6f7c850a11b7932692f07f1852a0c80cca)?

**Comment by njirap** [comment]
Hi  bhearsum I don't have that revision locally.. i get a "fatal: bad object" when i try to 'git show' it..

**Comment by bhearsum** [comment]
Yeah, you'll need to pull again. That revision in the merge commit from when I merged your pull request into balrog-ui: https://github.com/mozilla/balrog-ui/commit/47fcfe6f7c850a11b7932692f07f1852a0c80cca

**Comment by njirap** [comment]
Aah haha ok makes sense..

**Comment by njirap** [comment]
It's done..

**Pull request merged**
