### PR TITLE
Bug 1304555:Remove Product/Channel filter from Rules history pages

### PR DESCRIPTION
**Pull request by tpingili**
Product/Channel filter is shown in all pages where rule_id is not available and ng-if evaluates to true. rule_id is available in the history page, hence ng-if evaluates to false and the filter is removed from the DOM.

### CODE REVIEW

**Comment by NinadBhat** [comment]
@tpingili Thanks for you work. I will try to review the PR tonight.
Advice :- Please create different PR's for different bugs from next time.

**Comment by tpingili** [comment]
Thanks Ninad. Unintentionally, the second PR got tacked onto the first one. I'm learning how to create different PRs for my consecutive commits.

**Comment by NinadBhat** [comment]
@tpingili np. You can create different PR's by working on different branches. 
Your code for Bug 1304555 seems right.
As for  Bug 1301051 changing to "text" does the trick, but I am not sure if that is the right method, @mozbhearsum can you have a look and see if this is what we need.

@tpingili : let me know if you need help finding new bugs. bhearsum will be able to review this tomorrow.

**Comment by mozbhearsum** [comment]
Sorry for the push to your branch - I had to do it to get the CI tests to run! Please feel free to join us in IRC (irc://irc.mozilla.org/#balrog) if you'd like some help with git branches.

**Comment by mozbhearsum** [comment]
I was a bit concerned about accessibility problems if we change the inputs to type="text", but I asked some folks that know that space, and that should be fine.

You'll need to split up your patches into separate PRs before I can merge, though.

**Comment by NinadBhat** [comment]
@tpingili : I think the same error might also be caused at 
https://github.com/mozilla/balrog/blob/master/ui/app/templates/rule_scheduled_change_modal.html#L107
can you kindly make the changes there too.

**Comment by mozbhearsum** [comment]
I'd really love to get these things merged. Do you need a hand separating out the patches, @tpingili?

**Comment by mozbhearsum** [comment]
This was split into #259 and #260.

**Pull request closed without merging**
